### ISSUE TITLE
Files are missing

### ISSUE THREAD

**Issue by naapki** [niksauer/Krypton#115]
<img width="1128" alt="bez nazwy" src="https://user-images.githubusercontent.com/36900192/41153553-578f40f8-6b17-11e8-8506-6a0cc30420b5.png">

**Comment by niksauer** [comment]
Hi @naapki, this project uses `git submodules` to manage its dependencies. Therefore, setup becomes a two-step process.

1. `git clone <url>`
2. `git submodule update --recursive --init`

I will update the README accordingly, thanks!
